/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author hieud
 */
public class JpnHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form jpnHoaDon
     */
    public JpnHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBan1 = new javax.swing.JButton();
        btnBan2 = new javax.swing.JButton();
        btnBan3 = new javax.swing.JButton();
        btnBan4 = new javax.swing.JButton();
        btnBan5 = new javax.swing.JButton();
        btnBan6 = new javax.swing.JButton();
        btnBan7 = new javax.swing.JButton();
        btnBan8 = new javax.swing.JButton();
        btnBan9 = new javax.swing.JButton();
        btnBan10 = new javax.swing.JButton();
        btnBan11 = new javax.swing.JButton();
        btnBan12 = new javax.swing.JButton();
        btnBan13 = new javax.swing.JButton();
        btnBan14 = new javax.swing.JButton();
        btnBan15 = new javax.swing.JButton();
        btnBan16 = new javax.swing.JButton();
        btnBan17 = new javax.swing.JButton();
        btnBan18 = new javax.swing.JButton();
        btnBan19 = new javax.swing.JButton();
        btnBan20 = new javax.swing.JButton();
        plnHoaDon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlbMaHD = new javax.swing.JLabel();
        tfMaHD = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jlbNgayTao = new javax.swing.JLabel();
        tfNgayTao = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jlbKH = new javax.swing.JLabel();
        cmbLoaiKH = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jlbGioTao = new javax.swing.JLabel();
        tfGioTao = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jlbSDT = new javax.swing.JLabel();
        tfSoDT = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jlbThanhTien = new javax.swing.JLabel();
        tfThanhTien = new javax.swing.JTextField();
        jlbGiamGia = new javax.swing.JLabel();
        tfGiamGia = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jlbKachTra = new javax.swing.JLabel();
        tfKhachTra = new javax.swing.JTextField();
        jlbTienDu = new javax.swing.JLabel();
        tfTienDu = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbChiTietHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jpnBan = new javax.swing.JPanel();
        btnBan = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(230, 219, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        btnBan1.setBackground(new java.awt.Color(254, 254, 254));
        btnBan1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan1.setForeground(new java.awt.Color(102, 102, 102));
        btnBan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan1.setText("1");
        btnBan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan2.setBackground(new java.awt.Color(254, 254, 254));
        btnBan2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan2.setForeground(new java.awt.Color(102, 102, 102));
        btnBan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan2.setText("2");
        btnBan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan3.setBackground(new java.awt.Color(254, 254, 254));
        btnBan3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan3.setForeground(new java.awt.Color(102, 102, 102));
        btnBan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan3.setText("3");
        btnBan3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan4.setBackground(new java.awt.Color(254, 254, 254));
        btnBan4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan4.setForeground(new java.awt.Color(102, 102, 102));
        btnBan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan4.setText("4");
        btnBan4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan5.setBackground(new java.awt.Color(254, 254, 254));
        btnBan5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan5.setForeground(new java.awt.Color(102, 102, 102));
        btnBan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan5.setText("5");
        btnBan5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan6.setBackground(new java.awt.Color(230, 219, 209));
        btnBan6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan6.setForeground(new java.awt.Color(102, 102, 102));
        btnBan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan6.setText("6");
        btnBan6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan7.setBackground(new java.awt.Color(230, 219, 209));
        btnBan7.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan7.setForeground(new java.awt.Color(102, 102, 102));
        btnBan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan7.setText("7");
        btnBan7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan8.setBackground(new java.awt.Color(230, 219, 209));
        btnBan8.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan8.setForeground(new java.awt.Color(102, 102, 102));
        btnBan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan8.setText("8");
        btnBan8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan9.setBackground(new java.awt.Color(230, 219, 209));
        btnBan9.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan9.setForeground(new java.awt.Color(102, 102, 102));
        btnBan9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan9.setText("9");
        btnBan9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan10.setBackground(new java.awt.Color(230, 219, 209));
        btnBan10.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan10.setForeground(new java.awt.Color(102, 102, 102));
        btnBan10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan10.setText("10");
        btnBan10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan11.setBackground(new java.awt.Color(230, 219, 209));
        btnBan11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan11.setForeground(new java.awt.Color(102, 102, 102));
        btnBan11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan11.setText("11");
        btnBan11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBan12.setBackground(new java.awt.Color(230, 219, 209));
        btnBan12.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan12.setForeground(new java.awt.Color(102, 102, 102));
        btnBan12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan12.setText("12");
        btnBan12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan12ActionPerformed(evt);
            }
        });

        btnBan13.setBackground(new java.awt.Color(230, 219, 209));
        btnBan13.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan13.setForeground(new java.awt.Color(102, 102, 102));
        btnBan13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan13.setText("13");
        btnBan13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan13ActionPerformed(evt);
            }
        });

        btnBan14.setBackground(new java.awt.Color(230, 219, 209));
        btnBan14.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan14.setForeground(new java.awt.Color(102, 102, 102));
        btnBan14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan14.setText("14");
        btnBan14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan14ActionPerformed(evt);
            }
        });

        btnBan15.setBackground(new java.awt.Color(230, 219, 209));
        btnBan15.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan15.setForeground(new java.awt.Color(102, 102, 102));
        btnBan15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan15.setText("15");
        btnBan15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan15ActionPerformed(evt);
            }
        });

        btnBan16.setBackground(new java.awt.Color(230, 219, 209));
        btnBan16.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan16.setForeground(new java.awt.Color(102, 102, 102));
        btnBan16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan16.setText("16");
        btnBan16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan16ActionPerformed(evt);
            }
        });

        btnBan17.setBackground(new java.awt.Color(230, 219, 209));
        btnBan17.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan17.setForeground(new java.awt.Color(102, 102, 102));
        btnBan17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan17.setText("17");
        btnBan17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan17ActionPerformed(evt);
            }
        });

        btnBan18.setBackground(new java.awt.Color(230, 219, 209));
        btnBan18.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan18.setForeground(new java.awt.Color(102, 102, 102));
        btnBan18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan18.setText("18");
        btnBan18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan18ActionPerformed(evt);
            }
        });

        btnBan19.setBackground(new java.awt.Color(230, 219, 209));
        btnBan19.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan19.setForeground(new java.awt.Color(102, 102, 102));
        btnBan19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan19.setText("19");
        btnBan19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan19ActionPerformed(evt);
            }
        });

        btnBan20.setBackground(new java.awt.Color(230, 219, 209));
        btnBan20.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnBan20.setForeground(new java.awt.Color(102, 102, 102));
        btnBan20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan20.setText("20");
        btnBan20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnBan20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBan5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBan9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBan13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBan17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBan20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan1)
                    .addComponent(btnBan3)
                    .addComponent(btnBan2)
                    .addComponent(btnBan4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan5)
                    .addComponent(btnBan6)
                    .addComponent(btnBan7)
                    .addComponent(btnBan8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan9)
                    .addComponent(btnBan10)
                    .addComponent(btnBan11)
                    .addComponent(btnBan12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan13)
                    .addComponent(btnBan14)
                    .addComponent(btnBan15)
                    .addComponent(btnBan16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan17)
                    .addComponent(btnBan18)
                    .addComponent(btnBan19)
                    .addComponent(btnBan20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plnHoaDon.setBackground(new java.awt.Color(230, 219, 209));

        jPanel1.setBackground(new java.awt.Color(230, 219, 209));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jlbMaHD.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbMaHD.setText("Mã Hóa Đơn:");

        tfMaHD.setEditable(false);
        tfMaHD.setBackground(new java.awt.Color(230, 219, 209));
        tfMaHD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfMaHD.setText("HD001");
        tfMaHD.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jlbNgayTao.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbNgayTao.setText("Ngày Tạo:");

        tfNgayTao.setEditable(false);
        tfNgayTao.setBackground(new java.awt.Color(230, 219, 209));
        tfNgayTao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfNgayTao.setText("22/02/2022");
        tfNgayTao.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jlbKH.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbKH.setText("Khách Hàng:");

        cmbLoaiKH.setBackground(new java.awt.Color(230, 219, 209));
        cmbLoaiKH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmbLoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Thành Viên" }));
        cmbLoaiKH.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jlbGioTao.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbGioTao.setText("Giờ Tạo:");

        tfGioTao.setEditable(false);
        tfGioTao.setBackground(new java.awt.Color(230, 219, 209));
        tfGioTao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfGioTao.setText("15h00");
        tfGioTao.setBorder(null);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jlbSDT.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbSDT.setText("Điện Thoại:");

        tfSoDT.setBackground(new java.awt.Color(230, 219, 209));
        tfSoDT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfSoDT.setText("0366422258");
        tfSoDT.setBorder(null);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jlbThanhTien.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbThanhTien.setText("Thành Tiền:");

        tfThanhTien.setEditable(false);
        tfThanhTien.setBackground(new java.awt.Color(230, 219, 209));
        tfThanhTien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfThanhTien.setText("200.000");
        tfThanhTien.setBorder(null);

        jlbGiamGia.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbGiamGia.setText("Giảm Giá:");

        tfGiamGia.setEditable(false);
        tfGiamGia.setBackground(new java.awt.Color(230, 219, 209));
        tfGiamGia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfGiamGia.setText("10%");
        tfGiamGia.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jlbKachTra.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbKachTra.setText("Khách Trả:");

        tfKhachTra.setBackground(new java.awt.Color(230, 219, 209));
        tfKhachTra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfKhachTra.setText("500.000");
        tfKhachTra.setBorder(null);

        jlbTienDu.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jlbTienDu.setText("Tiền Dư:");

        tfTienDu.setEditable(false);
        tfTienDu.setBackground(new java.awt.Color(230, 219, 209));
        tfTienDu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tfTienDu.setText("320.000");
        tfTienDu.setBorder(null);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jtbChiTietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbChiTietHD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbKH)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbLoaiKH, 0, 1, Short.MAX_VALUE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbKachTra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbThanhTien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbMaHD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfMaHD))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlbNgayTao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNgayTao))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlbTienDu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfTienDu))
                                .addComponent(jSeparator5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlbGiamGia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbSDT)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlbGioTao)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfGioTao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMaHD)
                            .addComponent(tfMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNgayTao)
                            .addComponent(tfNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbGioTao)
                            .addComponent(tfGioTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbKH)
                            .addComponent(cmbLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbSDT)
                            .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbThanhTien)
                    .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiamGia)
                    .addComponent(tfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKachTra)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlbTienDu)
                        .addComponent(tfTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(230, 219, 209));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Bàn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        btnBan.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        btnBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/table_50px.png"))); // NOI18N
        btnBan.setToolTipText("");

        javax.swing.GroupLayout jpnBanLayout = new javax.swing.GroupLayout(jpnBan);
        jpnBan.setLayout(jpnBanLayout);
        jpnBanLayout.setHorizontalGroup(
            jpnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBan, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jpnBanLayout.setVerticalGroup(
            jpnBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(665, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plnHoaDonLayout = new javax.swing.GroupLayout(plnHoaDon);
        plnHoaDon.setLayout(plnHoaDonLayout);
        plnHoaDonLayout.setHorizontalGroup(
            plnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        plnHoaDonLayout.setVerticalGroup(
            plnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(plnHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan12ActionPerformed

    private void btnBan13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan13ActionPerformed

    private void btnBan14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan14ActionPerformed

    private void btnBan15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan15ActionPerformed

    private void btnBan16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan16ActionPerformed

    private void btnBan17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan17ActionPerformed

    private void btnBan18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan18ActionPerformed

    private void btnBan19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan19ActionPerformed

    private void btnBan20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBan20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnBan1;
    private javax.swing.JButton btnBan10;
    private javax.swing.JButton btnBan11;
    private javax.swing.JButton btnBan12;
    private javax.swing.JButton btnBan13;
    private javax.swing.JButton btnBan14;
    private javax.swing.JButton btnBan15;
    private javax.swing.JButton btnBan16;
    private javax.swing.JButton btnBan17;
    private javax.swing.JButton btnBan18;
    private javax.swing.JButton btnBan19;
    private javax.swing.JButton btnBan2;
    private javax.swing.JButton btnBan20;
    private javax.swing.JButton btnBan3;
    private javax.swing.JButton btnBan4;
    private javax.swing.JButton btnBan5;
    private javax.swing.JButton btnBan6;
    private javax.swing.JButton btnBan7;
    private javax.swing.JButton btnBan8;
    private javax.swing.JButton btnBan9;
    private javax.swing.JComboBox<String> cmbLoaiKH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlbGiamGia;
    private javax.swing.JLabel jlbGioTao;
    private javax.swing.JLabel jlbKH;
    private javax.swing.JLabel jlbKachTra;
    private javax.swing.JLabel jlbMaHD;
    private javax.swing.JLabel jlbNgayTao;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbThanhTien;
    private javax.swing.JLabel jlbTienDu;
    private javax.swing.JPanel jpnBan;
    private javax.swing.JTable jtbChiTietHD;
    private javax.swing.JPanel plnHoaDon;
    private javax.swing.JTextField tfGiamGia;
    private javax.swing.JTextField tfGioTao;
    private javax.swing.JTextField tfKhachTra;
    private javax.swing.JTextField tfMaHD;
    private javax.swing.JTextField tfNgayTao;
    private javax.swing.JTextField tfSoDT;
    private javax.swing.JTextField tfThanhTien;
    private javax.swing.JTextField tfTienDu;
    // End of variables declaration//GEN-END:variables
}
